import json
import os

cells = []

def md(source):
    cells.append({"cell_type": "markdown", "metadata": {},
                  "source": source, "id": f"md-{len(cells)}"})

def code(source):
    cells.append({"cell_type": "code", "metadata": {},
                  "source": source, "outputs": [],
                  "execution_count": None, "id": f"code-{len(cells)}"})

# === HEADER ===
md([
"# B09b: Graph Neural Networks (GNNs) - COMPSCI 713\n",
"\n",
"**Course:** COMPSCI 713 - AI Fundamentals  \n",
"**Lecture:** Week 10 - AI and Sustainability: GraphCast & GNNs  \n",
"**Instructor:** Dr Thomas Lacombe  \n",
"\n",
"This notebook covers Graph Neural Networks as presented in COMPSCI 713 Week 10.\n",
"It includes the GraphCast case study (AI for sustainability) and the fundamentals of\n",
"how GNNs process graph-structured data.\n",
"\n",
"**Key Idea:** Many real-world systems are naturally represented as graphs. GNNs learn\n",
"to process these structures by passing messages between nodes while preserving\n",
"permutation invariance/equivariance.\n",
"\n",
"**References:**\n",
"- Prince, S. J. (2023). *Understanding deep learning*. MIT press. Ch. 13\n",
"- Stanford CS224W: Machine Learning with Graphs\n",
"- Kipf & Welling (2016). Semi-supervised classification with GCNs\n",
"- Lam et al. (2023). Learning skillful medium-range global weather forecasting. *Science*"
])


# === TABLE OF CONTENTS ===
md([
"## Table of Contents\n",
"\n",
"1. [AI for Sustainability vs Sustainability of AI](#1)\n",
"2. [Case Study: GraphCast](#2)\n",
"3. [What is a Graph?](#3)\n",
"4. [Graph Representation](#4)\n",
"5. [Graph Neural Networks (GNNs)](#5)\n",
"6. [Graph Convolutional Networks (GCNs)](#6)\n",
"7. [Permutation Invariance and Equivariance](#7)\n",
"8. [GNN Tasks](#8)\n",
"9. [Hands-on: Building a Simple GCN](#9)\n",
"10. [Summary](#10)"
])

# === SETUP ===
md([
"---\n",
"## Setup\n",
"\n",
"Install and import required libraries."
])

code([
"# Setup - run this cell first\n",
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"import matplotlib.patches as mpatches\n",
"from matplotlib.lines import Line2D\n",
"\n",
"# For GNN implementation\n",
"try:\n",
"    import torch\n",
"    import torch.nn as nn\n",
"    import torch.nn.functional as F\n",
"    TORCH_AVAILABLE = True\n",
"except ImportError:\n",
"    TORCH_AVAILABLE = False\n",
"    print('PyTorch not available. Install with: pip install torch')\n",
"\n",
"np.random.seed(42)\n",
"print('Setup complete!')"
])


# === SECTION 1: AI FOR SUSTAINABILITY ===
md([
"---\n",
"<a id='1'></a>\n",
"## 1. AI for Sustainability vs Sustainability of AI\n",
"\n",
"### AI for Social Impact\n",
"\n",
'The area of "AI for Social Impact" or "AI for Social Good" is a fast-emerging field\n',
"that uses Artificial Intelligence to solve important societal problems.\n",
"\n",
"There are **two complementary perspectives**:\n",
"\n",
"| Concept | Definition | Examples |\n",
"|---------|-----------|----------|\n",
"| **AI for Sustainability** | Using AI to help solve sustainability problems | Weather forecasting (GraphCast), extreme event prediction, energy grid optimization |\n",
"| **Sustainability of AI** | Making AI development itself sustainable | Efficient models, green data centres, reduced carbon footprint |\n",
"\n",
"### Balancing Benefits and Risks\n",
"\n",
"According to the World Economic Forum (WEF), left unguided, AI *has the capability to accelerate\n",
"the environment's degradation*.\n",
"\n",
"- Many AI systems require enormous amounts of energy\n",
"- Global emissions from cloud computing may emit more carbon than commercial airlines\n",
"- By 2027, the AI industry could use as much energy as a country the size of the Netherlands\n",
"\n",
'### The "4Ms" of Sustainable ML\n',
"\n",
"Researchers at Google and UC Berkeley identified four levers to reduce AI's carbon footprint:\n",
"\n",
"1. **Model** - The ML algorithm (architecture efficiency)\n",
"2. **Machine** - The hardware (GPU/TPU efficiency)\n",
"3. **Mechanization** - The data centre (power delivery efficiency)\n",
"4. **Map** - Geographic location (clean energy supply)"
])


# === SECTION 2: GRAPHCAST ===
md([
"---\n",
"<a id='2'></a>\n",
"## 2. Case Study: GraphCast\n",
"\n",
"### Overview\n",
"\n",
"**GraphCast** (2023) by Google DeepMind is a weather forecasting system that uses\n",
"deep learning instead of traditional Numerical Weather Prediction (NWP) based on\n",
"physics equations.\n",
"\n",
"Key features:\n",
"- Uses a **Graph Neural Network** architecture\n",
"- Trained on **40 years** of historical weather data (ECMWF's ERA5 dataset)\n",
"- Gaps in data filled using traditional NWP\n",
"- Produces **10-day forecasts** faster and more accurately than traditional approaches (once trained)\n",
"\n",
"### Architecture\n",
"\n",
"GraphCast uses an **Encoder-Processor-Decoder** architecture:\n",
"\n",
"1. **Encoder:** Maps grid data to a multi-mesh graph representation\n",
"2. **Processor:** Applies message-passing GNN layers on the mesh\n",
"3. **Decoder:** Maps back from mesh to grid predictions\n",
"\n",
"### Input Weather State\n",
"\n",
"- 0.25\u00b0 latitude-longitude grid = **1M+ points**\n",
"- **227 variables** per point:\n",
"  - 5 surface variables\n",
"  - 6 atmospheric variables \u00d7 37 pressure levels\n",
"\n",
"### Why Graphs?\n",
"\n",
"The atmosphere is naturally modelled as a graph:\n",
"- **Nodes** = geographic locations on Earth's surface\n",
"- **Edges** = connections representing energy and mass transfers between regions\n",
"- Graph structure allows natural representation of complex spatial interactions\n",
"\n",
"### Autoregressive Forecasting\n",
"\n",
"GraphCast predicts the next weather state from the current state, then iteratively\n",
"applies itself to roll out multi-step forecasts (similar to how language models\n",
"generate text token by token).\n",
"\n",
"*Source: Lam, Remi, et al. (2023). Learning skillful medium-range global weather forecasting. Science 382.6677: 1416-1421.*"
])


# === SECTION 3: WHAT IS A GRAPH ===
md([
"---\n",
"<a id='3'></a>\n",
"## 3. What is a Graph?\n",
"\n",
"A **graph** $G = (V, E)$ is a general structure consisting of:\n",
"- A set of **nodes** (or vertices) $V$\n",
"- Connected by **edges** (or links) $E$\n",
"\n",
"Graphs are generally **sparse** structures (only a small subset of possible edges are present).\n",
"\n",
"### Real-World Examples\n",
"\n",
"Some objects **naturally** take the form of graphs:\n",
"- Road networks\n",
"- Molecules (atoms = nodes, bonds = edges)\n",
"- Electrical circuits\n",
"\n",
"But many other data types can be **structured as graphs**:\n",
"\n",
"| Domain | Nodes | Edges |\n",
"|--------|-------|-------|\n",
"| Social networks | People | Friendships |\n",
"| Scientific literature | Papers | Citations |\n",
"| Wikipedia | Articles | Hyperlinks |\n",
"| Computer programs | Variables/tokens | Computations |\n",
"| Point clouds | 3D points | Proximity connections |\n",
"| Scene representation | Scene elements | Spatial relationships |\n",
"| Weather (GraphCast) | Geographic locations | Atmospheric interactions |\n",
"\n",
"### Types of Graphs\n",
"\n",
"- **Undirected / Directed** - edges can be symmetric or asymmetric\n",
"- **Homogeneous / Heterogeneous** - nodes represent same or different entity types\n",
"- **Simple / Multi** - one or several edges between two nodes\n",
"- **Knowledge graphs** - directed heterogeneous multigraphs with typed edges"
])


# === GRAPH VISUALIZATION CODE ===
code([
"# Visualize a simple graph\n",
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
"\n",
"# Define a simple graph\n",
"node_positions = {\n",
"    0: (0.5, 2.0), 1: (1.5, 2.5), 2: (2.5, 2.0),\n",
"    3: (0.5, 1.0), 4: (1.5, 0.5), 5: (2.5, 1.0)\n",
"}\n",
"edges = [(0, 1), (0, 3), (1, 2), (1, 3), (1, 4), (2, 5), (3, 4), (4, 5)]\n",
"\n",
"# Plot the graph\n",
"ax = axes[0]\n",
"ax.set_title('Example Graph (6 nodes, 8 edges)', fontsize=13, fontweight='bold')\n",
"for (u, v) in edges:\n",
"    x = [node_positions[u][0], node_positions[v][0]]\n",
"    y = [node_positions[u][1], node_positions[v][1]]\n",
"    ax.plot(x, y, 'b-', linewidth=1.5, alpha=0.6)\n",
"for node, (x, y) in node_positions.items():\n",
"    ax.scatter(x, y, s=400, c='steelblue', zorder=5, edgecolors='darkblue', linewidth=2)\n",
"    ax.text(x, y, str(node+1), ha='center', va='center', fontsize=11,\n",
"            fontweight='bold', color='white')\n",
"ax.set_xlim(-0.2, 3.2)\n",
"ax.set_ylim(-0.2, 3.2)\n",
"ax.set_aspect('equal')\n",
"ax.axis('off')\n",
"\n",
"# Plot the adjacency matrix\n",
"N = 6\n",
"A = np.zeros((N, N))\n",
"for (u, v) in edges:\n",
"    A[u, v] = 1\n",
"    A[v, u] = 1  # undirected\n",
"\n",
"ax = axes[1]\n",
"ax.set_title('Adjacency Matrix A (6x6)', fontsize=13, fontweight='bold')\n",
"im = ax.imshow(A, cmap='Blues', vmin=0, vmax=1)\n",
"ax.set_xticks(range(N))\n",
"ax.set_yticks(range(N))\n",
"ax.set_xticklabels([str(i+1) for i in range(N)])\n",
"ax.set_yticklabels([str(i+1) for i in range(N)])\n",
"for i in range(N):\n",
"    for j in range(N):\n",
"        ax.text(j, i, int(A[i, j]), ha='center', va='center',\n",
"                fontsize=11, color='white' if A[i,j] > 0.5 else 'black')\n",
"ax.set_xlabel('Node')\n",
"ax.set_ylabel('Node')\n",
"\n",
"plt.tight_layout()\n",
"plt.show()\n",
"print(f'Graph has {N} nodes and {len(edges)} edges')\n",
"print(f'Adjacency matrix is symmetric (undirected): {np.allclose(A, A.T)}')\n",
"print(f'Diagonal is all zeros (no self-loops): {np.all(np.diag(A) == 0)}')"
])


# === SECTION 4: GRAPH REPRESENTATION ===
md([
"---\n",
"<a id='4'></a>\n",
"## 4. Graph Representation\n",
"\n",
"To apply deep learning to graphs, they need to be formally represented using matrices:\n",
"\n",
"### Adjacency Matrix $\\mathbf{A}$\n",
"\n",
"- Binary matrix of size $N \\times N$ (where $N$ = number of nodes)\n",
"- Element $(m, n)$ is 1 if node $m$ connects to node $n$, else 0\n",
"- **Symmetric** for undirected graphs, **asymmetric** for directed graphs\n",
"- Diagonal is 0 for simple graphs (no self-loops)\n",
"\n",
"### Node Data Matrix $\\mathbf{X}$\n",
"\n",
"- Matrix of size $D \\times N$ (or $N \\times F$ in some notations)\n",
"- Each column/row contains the **embedding** (feature vector) for one node\n",
"- $D$ (or $F$) = dimensionality of node features\n",
"\n",
"### Edge Data Matrix $\\mathbf{E}$\n",
"\n",
"- Matrix of size $D_E \\times E$ where $E$ = number of edges\n",
"- Each column contains the embedding for one edge\n",
"\n",
"### Adjacency Matrix as Context\n",
"\n",
"The adjacency matrix encodes structural information:\n",
"- $\\mathbf{A}$ contains the number of walks of length 1 between nodes\n",
"- $\\mathbf{A}^L$ contains the number of walks of length $L$ between nodes\n",
"- Pre-multiplying a node representation by $\\mathbf{A}$ gives information about\n",
"  the node's **local context** (its neighbors)"
])

code([
"# Demonstrate adjacency matrix powers and walks\n",
"print('=== Adjacency Matrix Properties ===')\n",
"print(f'\\nAdjacency matrix A (walks of length 1):')\n",
"print(A.astype(int))\n",
"\n",
"A2 = A @ A\n",
"print(f'\\nA^2 (walks of length 2):')\n",
"print(A2.astype(int))\n",
"\n",
"# Show what pre-multiplying by A does\n",
"# One-hot vector for node 4 (index 3)\n",
"x = np.zeros(N)\n",
"x[3] = 1  # node 4\n",
"print(f'\\nOne-hot vector for node 4: {x.astype(int)}')\n",
"print(f'A @ x (neighbors of node 4): {(A @ x).astype(int)}')\n",
"print(f'  -> Nodes reachable in 1 step from node 4: '\n",
"      f'{[i+1 for i in range(N) if (A @ x)[i] > 0]}')\n",
"\n",
"print(f'\\nA^2 @ x (2-step walks from node 4): {(A2 @ x).astype(int)}')\n",
"print(f'  -> Shows how many length-2 paths exist to each node from node 4')"
])


# === SECTION 5: GNNs ===
md([
"---\n",
"<a id='5'></a>\n",
"## 5. Graph Neural Networks (GNNs)\n",
"\n",
"### Definition\n",
"\n",
"> A GNN is an **optimisable transformation** on all attributes of the graph (nodes, edges)\n",
"> that **preserves graph symmetries** (permutation invariances).\n",
"\n",
"### Key Properties\n",
"\n",
"- Takes adjacency matrix $\\mathbf{A}$ and node feature matrix $\\mathbf{X}$ as input\n",
"- Node embeddings are updated after each layer to create hidden representations $\\mathbf{H}_k$\n",
"- Each hidden layer outputs updated node representations that include information about\n",
"  the node **itself** and its **context** within the graph\n",
"- Similar to word embeddings passing through a transformer: outputs include sentence context\n",
"\n",
"### Main Idea: Message Passing\n",
"\n",
"1. **Pass messages** between pairs of connected nodes\n",
"2. **Aggregate** messages at each node\n",
"3. **Update** node representations based on aggregated messages\n",
"\n",
"This refines node (and possibly edge) representations layer by layer.\n",
"\n",
"### Notation\n",
"\n",
"- Graph: $\\mathcal{G} = (\\mathbf{A}, \\mathbf{X})$\n",
"- Adjacency matrix: $\\mathbf{A} \\in \\mathbb{R}^{N \\times N}$\n",
"- Feature matrix: $\\mathbf{X} \\in \\mathbb{R}^{N \\times F}$\n",
"- Hidden state at layer $k$: $\\mathbf{H}_k$\n",
"- Flow: $\\mathbf{A}, \\mathbf{X} \\longrightarrow \\mathbf{H}_1 \\longrightarrow \\mathbf{H}_2 \\longrightarrow \\cdots \\longrightarrow \\mathbf{H}_K$\n",
"\n",
"### Why Not Use Classic MLPs?\n",
"\n",
"Classic MLPs are **not** permutation invariant/equivariant:\n",
"- Switching the order of input nodes leads to **different outputs**\n",
"- We need specialised architectures that respect graph structure!"
])


# === SECTION 6: GCNs ===
md([
"---\n",
"<a id='6'></a>\n",
"## 6. Graph Convolutional Networks (GCNs)\n",
"\n",
"### Overview\n",
"\n",
"A **GCN** is one type of GNN that updates each node by **aggregating information from\n",
"nearby nodes**.\n",
"\n",
"- Induces a **relational inductive bias**: prioritises information from neighbors\n",
"- Intuition: Nodes aggregate information from their neighbors using neural networks\n",
"\n",
"### Simple GCN Layer Formulation\n",
"\n",
"$$\\mathbf{h}_{k+1}^{(n)} = \\mathbf{a}\\left[\\boldsymbol{\\beta}_k + \\boldsymbol{\\Omega}_k \\mathbf{h}_k^{(n)} + \\boldsymbol{\\Omega}_k \\text{agg}[n]\\right]$$\n",
"\n",
"Where:\n",
"- $\\mathbf{h}_{k+1}^{(n)}$ = hidden representation for node $n$ at layer $k+1$\n",
"- $\\mathbf{h}_k^{(n)}$ = hidden representation for node $n$ at layer $k$\n",
"- $\\boldsymbol{\\beta}_k$ = bias term at layer $k$ (learnable)\n",
"- $\\boldsymbol{\\Omega}_k$ = weight matrix at layer $k$ (learnable)\n",
"- $\\text{agg}[n]$ = aggregation of neighbor representations\n",
"- $\\mathbf{a}[\\cdot]$ = non-linear activation (e.g., ReLU)\n",
"\n",
"### Key Design Choices\n",
"\n",
"**Parameters are shared across nodes:**\n",
"- Reduces the number of parameters\n",
"- Shares what the network learns at each node across the entire graph\n",
"\n",
"**Aggregation functions** (must be permutation invariant):\n",
"- Sum\n",
"- Average (mean)\n",
"- Max pooling\n",
"- Attention-weighted aggregation\n",
"\n",
"### Kipf & Welling GCN Layer (2016)\n",
"\n",
"The most well-known GCN formulation:\n",
"\n",
"$$\\mathbf{H}^{(l+1)} = \\sigma\\left(\\tilde{\\mathbf{D}}^{-1/2} \\tilde{\\mathbf{A}} \\tilde{\\mathbf{D}}^{-1/2} \\mathbf{H}^{(l)} \\mathbf{W}^{(l)}\\right)$$\n",
"\n",
"Where:\n",
"- $\\tilde{\\mathbf{A}} = \\mathbf{A} + \\mathbf{I}$ (adjacency with self-loops)\n",
"- $\\tilde{\\mathbf{D}}$ = degree matrix of $\\tilde{\\mathbf{A}}$\n",
"- $\\tilde{\\mathbf{D}}^{-1/2} \\tilde{\\mathbf{A}} \\tilde{\\mathbf{D}}^{-1/2}$ = symmetric normalisation\n",
"- $\\mathbf{H}^{(l)}$ = node embeddings before layer $l$\n",
"- $\\mathbf{W}^{(l)}$ = shared weight matrix at layer $l$\n",
"- $\\sigma$ = non-linearity (e.g., ReLU)"
])


# === GCN STEP BY STEP CODE ===
code([
"# Step-by-step GCN layer computation (NumPy)\n",
"print('=== GCN Layer Step-by-Step (Kipf & Welling) ===')\n",
"print()\n",
"\n",
"# Our graph from before\n",
"print('Step 1: Start with adjacency matrix A')\n",
"print(A.astype(int))\n",
"\n",
"# Add self-loops: A_tilde = A + I\n",
"A_tilde = A + np.eye(N)\n",
"print(f'\\nStep 2: Add self-loops -> A_tilde = A + I')\n",
"print(A_tilde.astype(int))\n",
"\n",
"# Compute degree matrix D_tilde\n",
"D_tilde = np.diag(A_tilde.sum(axis=1))\n",
"print(f'\\nStep 3: Degree matrix D_tilde (diagonal = row sums of A_tilde)')\n",
"print(D_tilde.astype(int))\n",
"\n",
"# Compute D^{-1/2}\n",
"D_inv_sqrt = np.diag(1.0 / np.sqrt(A_tilde.sum(axis=1)))\n",
"print(f'\\nStep 4: D_tilde^(-1/2)')\n",
"print(np.round(D_inv_sqrt, 3))\n",
"\n",
"# Normalized adjacency\n",
"A_norm = D_inv_sqrt @ A_tilde @ D_inv_sqrt\n",
"print(f'\\nStep 5: Normalized adjacency = D^(-1/2) @ A_tilde @ D^(-1/2)')\n",
"print(np.round(A_norm, 3))"
])

code([
"# Apply one GCN layer\n",
"print('=== Applying One GCN Layer ===')\n",
"print()\n",
"\n",
"# Random node features (N nodes, F=3 features each)\n",
"F_dim = 3\n",
"H = np.random.randn(N, F_dim)\n",
"print(f'Input node features H (shape {H.shape}):')\n",
"print(np.round(H, 3))\n",
"\n",
"# Random weight matrix (F_in -> F_out=2)\n",
"F_out = 2\n",
"W = np.random.randn(F_dim, F_out) * 0.5\n",
"print(f'\\nWeight matrix W (shape {W.shape}):')\n",
"print(np.round(W, 3))\n",
"\n",
"# GCN forward pass: H_new = ReLU(A_norm @ H @ W)\n",
"H_new = A_norm @ H @ W\n",
"print(f'\\nBefore activation (A_norm @ H @ W):')\n",
"print(np.round(H_new, 3))\n",
"\n",
"H_new = np.maximum(0, H_new)  # ReLU\n",
"print(f'\\nAfter ReLU activation (output embeddings):')\n",
"print(np.round(H_new, 3))\n",
"print(f'\\nEach row is the updated embedding for a node,')\n",
"print(f'incorporating information from its neighbors!')"
])


# === SECTION 7: PERMUTATION INVARIANCE/EQUIVARIANCE ===
md([
"---\n",
"<a id='7'></a>\n",
"## 7. Permutation Invariance and Equivariance\n",
"\n",
"Node indexing in graphs is **arbitrary** - permuting node indices does not change the\n",
"underlying graph (unlike pixels in images or words in text).\n",
"\n",
"Any processing applied to the graph should be **indifferent to index permutations**.\n",
"\n",
"### Permutation Invariance\n",
"\n",
"A function $f$ mapping a graph $G = (\\mathbf{A}, \\mathbf{X})$ to a $d$-dimensional embedding is\n",
"**permutation invariant** if:\n",
"\n",
"$$f(\\mathbf{A}_i, \\mathbf{X}_i) = f(\\mathbf{A}_j, \\mathbf{X}_j)$$\n",
"\n",
"for any orderings $i$ and $j$.\n",
"\n",
"\u2192 If you shuffle the nodes in the input, the overall **graph-level output** doesn't change.\n",
"\n",
"**Example:** Graph classification - the predicted class should be the same regardless of\n",
"how we number the nodes.\n",
"\n",
"### Permutation Equivariance\n",
"\n",
"A function $f$ mapping each node of $G$ to a $d$-dimensional embedding is\n",
"**permutation equivariant** if:\n",
"\n",
"$$f(\\mathbf{P}\\mathbf{A}\\mathbf{P}^\\top, \\mathbf{P}\\mathbf{X}) = \\mathbf{P} f(\\mathbf{A}, \\mathbf{X})$$\n",
"\n",
"for any permutation matrix $\\mathbf{P}$.\n",
"\n",
"\u2192 If you shuffle the nodes in the input, the **output node embeddings get shuffled in the same way**.\n",
"\n",
"**Example:** Node classification - each node's predicted class stays the same regardless of ordering.\n",
"\n",
"### GNNs and Permutation Properties\n",
"\n",
"Graph neural networks consist of multiple permutation equivariant/invariant functions:\n",
"- **GCN layers** are permutation equivariant (node embeddings follow the permutation)\n",
"- **Aggregation** (e.g., sum/mean over all nodes) is permutation invariant\n",
"- Combining equivariant layers + invariant readout = invariant graph-level predictions"
])


# === PERMUTATION DEMO CODE ===
code([
"# Demonstrate permutation equivariance of GCN\n",
"print('=== Permutation Equivariance Demo ===')\n",
"print()\n",
"\n",
"# Original ordering\n",
"print('Original node features H:')\n",
"print(np.round(H, 3))\n",
"\n",
"# Apply GCN with original ordering\n",
"out_original = np.maximum(0, A_norm @ H @ W)\n",
"print(f'\\nGCN output (original order):')\n",
"print(np.round(out_original, 3))\n",
"\n",
"# Create a permutation: swap nodes 0<->2, 1<->4\n",
"perm = [2, 4, 0, 3, 1, 5]  # new ordering\n",
"P = np.zeros((N, N))\n",
"for i, j in enumerate(perm):\n",
"    P[i, j] = 1\n",
"\n",
"# Permute the graph\n",
"H_perm = P @ H\n",
"A_tilde_perm = P @ A_tilde @ P.T\n",
"D_inv_sqrt_perm = np.diag(1.0 / np.sqrt(A_tilde_perm.sum(axis=1)))\n",
"A_norm_perm = D_inv_sqrt_perm @ A_tilde_perm @ D_inv_sqrt_perm\n",
"\n",
"# Apply GCN with permuted ordering\n",
"out_permuted = np.maximum(0, A_norm_perm @ H_perm @ W)\n",
"print(f'\\nGCN output (permuted order):')\n",
"print(np.round(out_permuted, 3))\n",
"\n",
"# Check equivariance: P @ out_original should equal out_permuted\n",
"out_original_permuted = P @ out_original\n",
"print(f'\\nP @ original output (should match permuted output):')\n",
"print(np.round(out_original_permuted, 3))\n",
"\n",
"print(f'\\nAre they equal? {np.allclose(out_permuted, out_original_permuted, atol=1e-10)}')\n",
"print('-> GCN is permutation EQUIVARIANT!')\n",
"\n",
"# Invariance: sum pooling gives same result regardless of order\n",
"graph_emb_original = out_original.sum(axis=0)\n",
"graph_emb_permuted = out_permuted.sum(axis=0)\n",
"print(f'\\nGraph-level embedding (sum pooling):')\n",
"print(f'  Original order: {np.round(graph_emb_original, 6)}')\n",
"print(f'  Permuted order:  {np.round(graph_emb_permuted, 6)}')\n",
"print(f'  Equal? {np.allclose(graph_emb_original, graph_emb_permuted)}')\n",
"print('-> Sum pooling makes it permutation INVARIANT!')"
])


# === SECTION 8: GNN TASKS ===
md([
"---\n",
"<a id='8'></a>\n",
"## 8. GNN Tasks\n",
"\n",
"GNNs can be applied to three main types of prediction tasks:\n",
"\n",
"### a) Graph Classification\n",
"\n",
"- **Goal:** Classify the entire graph into categories\n",
"- **Process:** GNN produces node embeddings \u2192 combine (e.g., average/sum) \u2192 classify\n",
"- **Example:** Predicting whether a molecule is toxic or not\n",
"\n",
"### b) Node Classification\n",
"\n",
"- **Goal:** Classify individual nodes\n",
"- **Process:** GNN produces node embeddings \u2192 classify each node independently\n",
"- **Example:** Predicting the role of a protein in a biological network\n",
"\n",
"### c) Edge Prediction (Link Prediction)\n",
"\n",
"- **Goal:** Predict whether an edge should exist between two nodes\n",
"- **Process:** GNN produces node embeddings \u2192 combine adjacent embeddings (e.g., dot product) \u2192 predict edge probability\n",
"- **Example:** Recommending friends in a social network\n",
"\n",
"### Connection to GraphCast\n",
"\n",
"GraphCast performs a **node-level regression** task:\n",
"- Each node represents a geographic location\n",
"- The GNN predicts the next weather state (temperature, pressure, etc.) at each node\n",
"- This is permutation equivariant: the prediction for Auckland doesn't depend on how we number the grid points"
])


# === SECTION 9: HANDS-ON GCN ===
md([
"---\n",
"<a id='9'></a>\n",
"## 9. Hands-on: Building a Simple GCN with PyTorch\n",
"\n",
"Let's implement a simple 2-layer GCN for node classification on a small graph.\n",
"\n",
"We'll use the **Karate Club** graph - a classic social network dataset where\n",
"34 members of a karate club split into 2 groups after a dispute."
])

code([
"if not TORCH_AVAILABLE:\n",
"    print('PyTorch required for this section. Skipping...')\n",
"else:\n",
"    # Define a simple GCN layer\n",
"    class GCNLayer(nn.Module):\n",
"        \"\"\"Single Graph Convolutional Layer (Kipf & Welling 2016)\"\"\"\n",
"        def __init__(self, in_features, out_features):\n",
"            super().__init__()\n",
"            self.W = nn.Parameter(torch.randn(in_features, out_features) * 0.1)\n",
"            self.b = nn.Parameter(torch.zeros(out_features))\n",
"\n",
"        def forward(self, A_norm, H):\n",
"            # H_new = ReLU(A_norm @ H @ W + b)\n",
"            return F.relu(A_norm @ H @ self.W + self.b)\n",
"\n",
"    class SimpleGCN(nn.Module):\n",
"        \"\"\"2-layer GCN for node classification\"\"\"\n",
"        def __init__(self, n_features, n_hidden, n_classes):\n",
"            super().__init__()\n",
"            self.gcn1 = GCNLayer(n_features, n_hidden)\n",
"            self.gcn2 = GCNLayer(n_hidden, n_classes)\n",
"\n",
"        def forward(self, A_norm, X):\n",
"            H = self.gcn1(A_norm, X)\n",
"            H = self.gcn2(A_norm, H)\n",
"            return H  # logits for each node\n",
"\n",
"    print('GCN model defined!')\n",
"    print()\n",
"    print('Architecture:')\n",
"    print('  Input features -> GCN Layer 1 (+ ReLU) -> Hidden')\n",
"    print('  Hidden -> GCN Layer 2 (+ ReLU) -> Class logits')"
])


code([
"if TORCH_AVAILABLE:\n",
"    # Create a small example graph (simplified Karate Club)\n",
"    # 10 nodes, 2 communities\n",
"    edges_list = [\n",
"        (0,1),(0,2),(0,3),(1,2),(1,3),(2,3),  # community 1 (dense)\n",
"        (4,5),(4,6),(5,6),(5,7),(6,7),(7,8),(7,9),(8,9),  # community 2\n",
"        (3,4),(3,5)  # bridge edges between communities\n",
"    ]\n",
"    n_nodes = 10\n",
"    labels = torch.tensor([0,0,0,0, 1,1,1,1,1,1])  # 2 classes\n",
"\n",
"    # Build adjacency matrix\n",
"    A_small = torch.zeros(n_nodes, n_nodes)\n",
"    for (u, v) in edges_list:\n",
"        A_small[u, v] = 1\n",
"        A_small[v, u] = 1\n",
"\n",
"    # Normalize: A_norm = D^{-1/2} (A + I) D^{-1/2}\n",
"    A_hat = A_small + torch.eye(n_nodes)\n",
"    D_hat = torch.diag(A_hat.sum(dim=1))\n",
"    D_inv_sqrt = torch.diag(1.0 / torch.sqrt(A_hat.sum(dim=1)))\n",
"    A_norm_t = D_inv_sqrt @ A_hat @ D_inv_sqrt\n",
"\n",
"    # Node features: use one-hot encoding (identity matrix)\n",
"    X = torch.eye(n_nodes)\n",
"\n",
"    print(f'Graph: {n_nodes} nodes, {len(edges_list)} edges')\n",
"    print(f'Node features: {X.shape[1]}-dimensional (one-hot)')\n",
"    print(f'Labels: {labels.tolist()}')\n",
"    print(f'Community 1 (label 0): nodes 0-3')\n",
"    print(f'Community 2 (label 1): nodes 4-9')"
])

code([
"if TORCH_AVAILABLE:\n",
"    # Train the GCN\n",
"    model = SimpleGCN(n_features=n_nodes, n_hidden=8, n_classes=2)\n",
"    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)\n",
"    criterion = nn.CrossEntropyLoss()\n",
"\n",
"    # Training loop\n",
"    losses = []\n",
"    for epoch in range(200):\n",
"        model.train()\n",
"        optimizer.zero_grad()\n",
"        out = model(A_norm_t, X)\n",
"        loss = criterion(out, labels)\n",
"        loss.backward()\n",
"        optimizer.step()\n",
"        losses.append(loss.item())\n",
"\n",
"    # Evaluate\n",
"    model.eval()\n",
"    with torch.no_grad():\n",
"        predictions = model(A_norm_t, X).argmax(dim=1)\n",
"\n",
"    accuracy = (predictions == labels).float().mean().item()\n",
"    print(f'Training complete! Final loss: {losses[-1]:.4f}')\n",
"    print(f'Accuracy: {accuracy*100:.1f}%')\n",
"    print(f'Predictions: {predictions.tolist()}')\n",
"    print(f'True labels: {labels.tolist()}')\n",
"\n",
"    # Plot training loss\n",
"    plt.figure(figsize=(8, 4))\n",
"    plt.plot(losses)\n",
"    plt.xlabel('Epoch')\n",
"    plt.ylabel('Cross-Entropy Loss')\n",
"    plt.title('GCN Training Loss (Node Classification)')\n",
"    plt.grid(True, alpha=0.3)\n",
"    plt.tight_layout()\n",
"    plt.show()"
])


code([
"if TORCH_AVAILABLE:\n",
"    # Visualize the learned node embeddings\n",
"    model.eval()\n",
"    with torch.no_grad():\n",
"        # Get intermediate embeddings (after first GCN layer)\n",
"        H1 = model.gcn1(A_norm_t, X)\n",
"\n",
"    # Project to 2D for visualization using first 2 dimensions\n",
"    embeddings = H1.numpy()\n",
"\n",
"    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
"\n",
"    # Plot graph with true labels\n",
"    ax = axes[0]\n",
"    ax.set_title('Graph with True Labels', fontsize=13, fontweight='bold')\n",
"    pos = {\n",
"        0: (0, 1), 1: (1, 2), 2: (1, 0), 3: (2, 1),\n",
"        4: (3, 1), 5: (3, 2), 6: (4, 0), 7: (4, 1.5),\n",
"        8: (5, 0.5), 9: (5, 2)\n",
"    }\n",
"    colors = ['#FF6B6B' if l == 0 else '#4ECDC4' for l in labels]\n",
"    for (u, v) in edges_list:\n",
"        ax.plot([pos[u][0], pos[v][0]], [pos[u][1], pos[v][1]],\n",
"                'gray', alpha=0.4, linewidth=1)\n",
"    for i in range(n_nodes):\n",
"        ax.scatter(pos[i][0], pos[i][1], c=colors[i], s=300,\n",
"                   zorder=5, edgecolors='black', linewidth=1.5)\n",
"        ax.text(pos[i][0], pos[i][1], str(i), ha='center', va='center',\n",
"                fontsize=10, fontweight='bold')\n",
"    ax.legend(handles=[\n",
"        mpatches.Patch(color='#FF6B6B', label='Community 0'),\n",
"        mpatches.Patch(color='#4ECDC4', label='Community 1')\n",
"    ])\n",
"    ax.axis('off')\n",
"\n",
"    # Plot learned embeddings\n",
"    ax = axes[1]\n",
"    ax.set_title('Learned Node Embeddings (first 2 dims)', fontsize=13, fontweight='bold')\n",
"    for i in range(n_nodes):\n",
"        ax.scatter(embeddings[i, 0], embeddings[i, 1], c=colors[i], s=200,\n",
"                   edgecolors='black', linewidth=1.5, zorder=5)\n",
"        ax.annotate(str(i), (embeddings[i, 0], embeddings[i, 1]),\n",
"                    fontsize=9, ha='center', va='bottom', xytext=(0, 8),\n",
"                    textcoords='offset points')\n",
"    ax.set_xlabel('Dimension 1')\n",
"    ax.set_ylabel('Dimension 2')\n",
"    ax.grid(True, alpha=0.3)\n",
"    ax.legend(handles=[\n",
"        mpatches.Patch(color='#FF6B6B', label='Community 0'),\n",
"        mpatches.Patch(color='#4ECDC4', label='Community 1')\n",
"    ])\n",
"\n",
"    plt.tight_layout()\n",
"    plt.show()\n",
"    print('Nodes from the same community cluster together in embedding space!')"
])


# === SECTION 10: SUMMARY ===
md([
"---\n",
"<a id='10'></a>\n",
"## 10. Summary\n",
"\n",
"### Key Takeaways\n",
"\n",
"1. **AI for sustainability** focuses on using AI to solve sustainability problems\n",
"   (e.g., GraphCast for weather forecasting, extreme event prediction)\n",
"\n",
"2. **Sustainability of AI** focuses on making AI development itself sustainable\n",
"   (e.g., more efficient models, green computing via the 4Ms)\n",
"\n",
"3. **GraphCast** is a weather forecast system that improves on classic physical models\n",
"   by leveraging 40 years of historical data and graph neural networks\n",
"\n",
"4. **Graphs** are structures that represent data by connecting nodes with edges.\n",
"   They can be represented with adjacency matrices and node/edge embeddings\n",
"\n",
"5. **Graph Neural Networks** learn permutation invariant and equivariant functions\n",
"   to transform graph embeddings, solving tasks such as:\n",
"   - Graph classification\n",
"   - Node classification\n",
"   - Edge prediction\n",
"\n",
"6. **GCNs** update each node by aggregating information from neighbors using\n",
"   shared weight matrices and non-linear activations\n",
"\n",
"7. **Permutation invariance** means the graph-level output doesn't change when\n",
"   nodes are reordered. **Permutation equivariance** means node outputs get\n",
"   reordered in the same way as the input.\n",
"\n",
"### Exam Checklist\n",
"\n",
"- [ ] Define AI for sustainability vs sustainability of AI with examples\n",
"- [ ] Describe GraphCast's architecture and purpose\n",
"- [ ] Define graphs (nodes, edges) and give real-world examples\n",
"- [ ] Explain adjacency matrices and what $\\mathbf{A}^L$ represents\n",
"- [ ] Explain the GCN layer update rule\n",
"- [ ] Define permutation invariance and equivariance\n",
"- [ ] Explain why MLPs are not suitable for graphs\n",
"- [ ] List common GNN tasks (graph/node/edge level)\n",
"\n",
"### Further Reading\n",
"\n",
"- Prince, S. J. (2023). *Understanding deep learning*. MIT press. Chapter 13.\n",
"- Kipf & Welling (2016). Semi-supervised classification with graph convolutional networks.\n",
"- Stanford CS224W: Machine Learning with Graphs (slides and notebooks online)\n",
"- Lam et al. (2023). Learning skillful medium-range global weather forecasting. *Science*.\n",
"- Corso et al. (2024). Graph neural networks. *Nature Reviews Methods Primers*, 4(1), 17."
])


# === BUILD THE NOTEBOOK ===
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

output_path = "Basic/B09b - Graph Neural Networks (COMPSCI 713).ipynb"
with open(output_path, 'w') as f:
    json.dump(notebook, f, indent=1)

print(f"Notebook written to: {output_path}")
print(f"Total cells: {len(cells)}")
